version: 2.1
orbs:
  coveralls: coveralls/coveralls@2.1.0
jobs:
  build:
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run:
          name: Upload coverage to Coveralls
          command: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      - run: npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN
